name: pretest_mdi_pai
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  firebase_core: ^2.17.0
  get: 4.6.6
  firebase_auth: ^4.10.1
  google_sign_in: ^6.1.5
  google_fonts: ^6.1.0
  sizer: ^2.0.15
  flutter_svg: ^2.0.7
  dio: ^5.3.3
  form_builder_validators: ^9.1.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/

